site_name: Hierarchical Configuration
site_url: https://hier-config.readthedocs.io/
repo_url: https://github.com/netdevops/hier_config
theme:
  name: readthedocs

nav:
- Home: index.md
- Install: install.md
- Getting Started: getting-started.md
- Config View: config-view.md
- Drivers: drivers.md
- Custom Workflows: custom-workflows.md
- Future Config: future-config.md
- JunOS Style Syntax Remediation: junos-style-syntax-remediation.md
- Unified Diff: unified-diff.md
- Utilities: utilities.md
- Working with Tags: tags.md
- Remediation Reporting: remediation-reporting.md
